version: '3'

services:
  web:
    container_name: aslcv2_be
    build: aslcv2_be/
    command: /usr/local/src/aslcv2_be/srv/docker/gunicorn_start.bash
    ports:
      - 8009:8009
    network_mode: "host"