version: '3'

services:
  web:
    container_name: aslcv2_be
    image: ggetzie/aslcv2_be_web:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      gunicorn config.wsgi:application --name aslcv2_be --workers 4 --timeout 120 --bind 0.0.0.0:8009
    ports:
      - 8009:8009
    network_mode: "bridge"
    env_file:
      - aslcv2_be.env
    volumes:
      - /C/aslcv2_be/staticfiles:/usr/local/src/aslcv2_be/staticfiles
      - /C/aslcv2_be/media:/usr/local/src/aslcv2_be/media
      - /C/aslcv2_be/logs:/usr/local/src/aslcv2_be/logs

# volumes:
#      staticfiles:
#      media:

