version: '3'

services:
  web:
    container_name: aslcv2_be
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      gunicorn config.wsgi:application --name aslcv2_be --workers 4 --timeout 120 --bind 0.0.0.0:8009
    ports:
      - 8009:8009
    network_mode: "bridge"
    env_file:
      - aslcv2_be.env
    volumes:
      - ./staticfiles://C/Users/ggetz/Documents/GitHub/aslcv2_be/staticfiles
      - ./media://C/Users/ggetz/Documents/GitHub/aslcv2_be/media

# volumes:
#      staticfiles:
#      media:

