CREATE SCHEMA django;
GRANT ALL ON SCHEMA django TO dbrw;
GRANT ALL ON ALL TABLES IN SCHEMA django TO dbrw;
GRANT ALL ON ALL SEQUENCES IN SCHEMA django TO dbrw;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA django TO dbrw;
