# Generated by Django 3.0.10 on 2020-09-20 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255, verbose_name='Material')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Material Category',
                'verbose_name_plural': 'Material Categories',
                'db_table': 'options_material_category',
            },
        ),
        migrations.CreateModel(
            name='ObjectFind',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('find_number', models.IntegerField(verbose_name='Find Number')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('director_notes', models.TextField(blank=True, default='', verbose_name='Director Notes')),
            ],
            options={
                'verbose_name': 'Object Find',
                'verbose_name_plural': 'Object Finds',
                'db_table': 'object_finds',
                'ordering': ['spatial_context__spatial_area__utm_hemisphere', 'spatial_context__spatial_area__utm_zone', 'spatial_context__spatial_area__area_utm_easting_meters', 'spatial_context__spatial_area__area_utm_northing_meters', 'spatial_context__context_number', 'find_number'],
            },
        ),
        migrations.CreateModel(
            name='ObjectPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(height_field='height', upload_to=main.models.get_object_folder, width_field='width')),
                ('height', models.IntegerField(verbose_name='Height')),
                ('width', models.IntegerField(verbose_name='Width')),
            ],
            options={
                'verbose_name': 'Object Photo',
                'verbose_name_plural': 'Object Photos',
                'db_table': 'object_photos',
            },
        ),
        migrations.CreateModel(
            name='SpatialArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('utm_hemisphere', models.CharField(choices=[('N', 'North'), ('S', 'South')], max_length=1, verbose_name='UTM Hemisphere')),
                ('utm_zone', models.IntegerField(verbose_name='UTM Zone')),
                ('area_utm_easting_meters', models.IntegerField(verbose_name='Easting (meters)')),
                ('area_utm_northing_meters', models.IntegerField(verbose_name='Northing (meters)')),
                ('type', models.CharField(blank=True, default='', max_length=255, verbose_name='Type')),
                ('longitude_decimal_degrees', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('latitude_decimal_degrees', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
            ],
            options={
                'verbose_name': 'Spatial Area',
                'verbose_name_plural': 'Spatial Areas',
                'db_table': 'spatial_areas',
                'ordering': ['utm_hemisphere', 'utm_zone', 'area_utm_easting_meters', 'area_utm_northing_meters'],
            },
        ),
        migrations.CreateModel(
            name='SpatialContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_number', models.IntegerField(editable=False, verbose_name='Context Number')),
                ('type', models.CharField(max_length=255, verbose_name='Context Type')),
                ('opening_date', models.DateTimeField(blank=True, null=True, verbose_name='Opening Date')),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='Closing Date')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('director_notes', models.TextField(blank=True, default='', verbose_name='Director Notes')),
                ('spatial_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SpatialArea')),
            ],
            options={
                'verbose_name': 'Spatial Context',
                'verbose_name_plural': 'Spatial Contexts',
                'db_table': 'spatial_contexts',
                'ordering': ['spatial_area__utm_hemisphere', 'spatial_area__utm_zone', 'spatial_area__area_utm_easting_meters', 'spatial_area__area_utm_northing_meters', 'context_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='spatialarea',
            constraint=models.UniqueConstraint(fields=('utm_hemisphere', 'utm_zone', 'area_utm_easting_meters', 'area_utm_northing_meters'), name='unique_spatial_area'),
        ),
        migrations.AddField(
            model_name='objectphoto',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SpatialContext'),
        ),
        migrations.AddField(
            model_name='objectphoto',
            name='object_find',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ObjectFind'),
        ),
        migrations.AddField(
            model_name='objectphoto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objectfind',
            name='material_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.MaterialCategory'),
        ),
        migrations.AddField(
            model_name='objectfind',
            name='spatial_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SpatialContext'),
        ),
        migrations.AddField(
            model_name='objectfind',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='materialcategory',
            constraint=models.UniqueConstraint(fields=('material', 'category'), name='unique_material_category'),
        ),
        migrations.AddConstraint(
            model_name='spatialcontext',
            constraint=models.UniqueConstraint(fields=('spatial_area', 'context_number'), name='unique_spatial_context'),
        ),
        migrations.AddConstraint(
            model_name='objectfind',
            constraint=models.UniqueConstraint(fields=('spatial_context', 'find_number'), name='unique_object_find'),
        ),
    ]
