# Generated by Django 3.0.10 on 2020-11-16 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaType',
            fields=[
                ('type', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Type')),
            ],
            options={
                'db_table': 'area_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContextType',
            fields=[
                ('type', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Type')),
            ],
            options={
                'db_table': 'context_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=255, verbose_name='Material')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Material Category',
                'verbose_name_plural': 'Material Categories',
                'db_table': 'material_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectFind',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('utm_hemisphere', models.CharField(choices=[('N', 'North'), ('S', 'South')], max_length=1, verbose_name='UTM Hemisphere')),
                ('utm_zone', models.IntegerField(verbose_name='UTM Zone')),
                ('area_utm_easting_meters', models.IntegerField(verbose_name='Easting (meters)')),
                ('area_utm_northing_meters', models.IntegerField(verbose_name='Northing (meters)')),
                ('context_number', models.IntegerField(editable=False, verbose_name='Context Number')),
                ('find_number', models.IntegerField(verbose_name='Find Number')),
                ('material', models.CharField(default='', max_length=255, verbose_name='Material')),
                ('category', models.CharField(default='', max_length=255, verbose_name='Category')),
                ('director_notes', models.TextField(blank=True, default='', verbose_name='Director Notes')),
            ],
            options={
                'verbose_name': 'Object Find',
                'verbose_name_plural': 'Object Finds',
                'db_table': 'finds',
                'ordering': ['utm_hemisphere', 'utm_zone', 'area_utm_easting_meters', 'area_utm_northing_meters', 'context_number', 'find_number'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpatialArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('utm_hemisphere', models.CharField(choices=[('N', 'North'), ('S', 'South')], max_length=1, verbose_name='UTM Hemisphere')),
                ('utm_zone', models.IntegerField(verbose_name='UTM Zone')),
                ('area_utm_easting_meters', models.IntegerField(verbose_name='Easting (meters)')),
                ('area_utm_northing_meters', models.IntegerField(verbose_name='Northing (meters)')),
                ('longitude_decimal_degrees', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('latitude_decimal_degrees', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
            ],
            options={
                'verbose_name': 'Spatial Area',
                'verbose_name_plural': 'Spatial Areas',
                'db_table': 'areas',
                'ordering': ['utm_hemisphere', 'utm_zone', 'area_utm_easting_meters', 'area_utm_northing_meters'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpatialContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('utm_hemisphere', models.CharField(choices=[('N', 'North'), ('S', 'South')], max_length=1, verbose_name='UTM Hemisphere')),
                ('utm_zone', models.IntegerField(verbose_name='UTM Zone')),
                ('area_utm_easting_meters', models.IntegerField(verbose_name='Easting (meters)')),
                ('area_utm_northing_meters', models.IntegerField(verbose_name='Northing (meters)')),
                ('context_number', models.IntegerField(editable=False, verbose_name='Context Number')),
                ('opening_date', models.DateTimeField(blank=True, null=True, verbose_name='Opening Date')),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='Closing Date')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('director_notes', models.TextField(blank=True, default='', verbose_name='Director Notes')),
            ],
            options={
                'verbose_name': 'Spatial Context',
                'verbose_name_plural': 'Spatial Contexts',
                'db_table': 'contexts',
                'ordering': ['utm_hemisphere', 'utm_zone', 'area_utm_easting_meters', 'area_utm_northing_meters', 'context_number'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContextPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('utm_hemisphere', models.CharField(choices=[('N', 'North'), ('S', 'South')], max_length=1, verbose_name='UTM Hemisphere')),
                ('utm_zone', models.IntegerField(verbose_name='UTM Zone')),
                ('area_utm_easting_meters', models.IntegerField(verbose_name='Easting (meters)')),
                ('area_utm_northing_meters', models.IntegerField(verbose_name='Northing (meters)')),
                ('context_number', models.IntegerField(editable=False, verbose_name='Context Number')),
                ('photo', models.ImageField(upload_to=main.models.get_context_folder)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Context Photo',
                'verbose_name_plural': 'Context Photos',
                'db_table': 'context_photos',
            },
        ),
    ]
