# Generated by Django 3.1.3 on 2021-01-04 08:03

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areatype',
            options={'managed': False, 'ordering': ['type'], 'verbose_name': 'Area Type', 'verbose_name_plural': 'Area Types'},
        ),
        migrations.AlterModelOptions(
            name='contexttype',
            options={'managed': False, 'ordering': ['type'], 'verbose_name': 'Context Type', 'verbose_name_plural': 'Context Types'},
        ),
        migrations.AddField(
            model_name='contextphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_context_folder),
        ),
    ]
