# Generated by Django 3.0.10 on 2020-09-20 01:48

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200920_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectphoto',
            name='height',
        ),
        migrations.RemoveField(
            model_name='objectphoto',
            name='width',
        ),
        migrations.AlterField(
            model_name='objectphoto',
            name='photo',
            field=models.ImageField(upload_to=main.models.get_object_folder),
        ),
    ]
