# Generated by Django 3.0.10 on 2020-09-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200920_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialcontext',
            name='type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Context Type'),
        ),
    ]
