# Generated by Django 3.2.18 on 2024-04-16 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_surveypath_surveypoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveypoint',
            name='survey_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='main.surveypath'),
        ),
    ]
