# Generated by Django 3.2.18 on 2024-05-02 02:22

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_surveypoint_survey_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findphoto',
            name='photo',
            field=models.FileField(upload_to=main.models.get_findphoto_folder),
        ),
    ]
